default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: preim
  password: preim

development:
  <<: *default
  database: rent200_backend_development

test:
  <<: *default
  database: rent200_backend_test


production:
  <<: *default
  database: rent200_backend_production
